### PR TITLE
Add a backend for logins

### PR DESCRIPTION
**Pull request by noahl**
Use djoser to manage logins with a REST API. This commit just includes
a basic, functional backend. There is no user interface and no
customization of djoser.

### CODE REVIEW

**Comment by elyezer** [comment]
> Also please include a small example of how someone can authenticate against the new endpoint. In the rest-api-examples.rst doc's "Authorization" section probably fits best that.

QE appreciates those examples :smile:

**Comment by noahl** [comment]
@infinitewarp I just pushed a change that I think addresses your comment. Please take a look.

**Comment by noahl** [comment]
@ilyavw the old commands should still work! I believe djoser is providing a REST interface to the same Django `User` objects that the standard Django tools use.

**Comment by ilyavw** [comment]
@noahl I realize the old commands still work, but this seemed like a good time to start transitioning away from those as I see them eventually being phased out.

**Pull request merged**
