### PR TITLE
remove redundant CloudAccount.name attribute

### PR DESCRIPTION
**Pull request by infinitewarp**

### CODE REVIEW

**Review by katherine-black — DISMISSED** [review]
👍

**Review by katherine-black — APPROVED** [review]

**Comment by katherine-black** [comment]
@infinitewarp I'm seeing repeated smoke test failures, I'm guessing @paraggit will have to update the smoke tests with the new responses since we're no longer sending the name.

**Review by katherine-black — CHANGES_REQUESTED** [review]
Smoke tests appear to need to be updated.

**Comment by paraggit** [comment]
I will incorporate the openapi changes to the IQE-cloudmeter plugin.

**Review by katherine-black — APPROVED** [review]

**Pull request merged**
